name: Python Package Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: tetris

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Create tarball
        run: |
          tar --exclude=.git --exclude=.github -czvf ${PROJECT_NAME}-linux-macos.tar.gz . --ignore-failed-read
          ls -la ${PROJECT_NAME}-linux-macos.tar.gz

      - name: Upload Release Assets to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ env.PROJECT_NAME }}-linux-macos.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest

    env:
      PROJECT_NAME: tetris

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Debug - Kiểm tra thư mục hiện tại
        run: |
          Get-Location
          Get-ChildItem -Path . -Name

      - name: Create zip archive
        run: |
          $zipPath = "${{ env.PROJECT_NAME }}-windows.zip"

          # Xóa file cũ nếu tồn tại
          if (Test-Path $zipPath) {
            Remove-Item $zipPath -Force
          }

          # Nén toàn bộ project vào file ZIP
          Get-ChildItem -Path . -Exclude .git, .github | Compress-Archive -DestinationPath $zipPath

          # Kiểm tra kết quả nén
          Get-Item $zipPath
        shell: pwsh

      - name: Upload Release Assets to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ env.PROJECT_NAME }}-windows.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
